#!/usr/bin/env bash

question=$(echo "Lock|Logout|Reboot|Shutdown|Suspend" | rofi -sep "|" \
    -dmenu -i -p 'System: ' "" -width 20 -hide-scrollbar \
    -eh 1 -line-padding 4 -padding 20 -lines 5 -color-enabled)

case $question in
    *Lock)
        swaylock
        ;;
    *Logout)
        loginctl terminate-user $USER
        ;;
    *Reboot)
        systemctl reboot
        ;;
    *Shutdown)
        systemctl poweroff
        ;;
    *Suspend)
        systemctl suspend
        ;;
    *)
        exit 0  # do nothing on wrong response
        ;;
esac
