#! /bin/sh

sxhkd &

tint2 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating #follow=on desktop='^8' 
bspc rule -a gsimplecal state=floating
bspc rule -a Chromium #desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#fix_xcursor &
picom -b &
nm-applet &
#blueman-tray &
fcitx &
xfce4-power-manager &
redshift-gtk &
variety &
setxkbmap -layout gb &
pamac-tray &
volumeicon &
xfsettingsd &
xfce4-volumed-pulse &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
gnome-keyring-daemon --start --components=pkcs11 &
